sudo: required
language: bash

env:
  - container_id=${container_id:-$timestamp}
 
services:
  - docker
  
stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
        - export container_id=$(date +%s)
        - export cleanup=false
        - docker swarm init
        - docker stack deploy -c stackfile.yml bitroid
        - sleep 90
        - docker service ps bitroid_app
        - docker service ls
        - echo "Listing files"
        - ls -la
        - wget -O- localhost:8080
    
    - stage: deploy
      script: curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/bitroid/bitroiddocker/trigger/d41af848-1632-491c-b3c9-364c1639dceb/
      
notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
