language: bash

env:
  - container_id=${container_id:-$timestamp}
 
services:
  - docker

script:
#create a random file to store the container
  - export container_id=$(date +%s)
  - export cleanup=false

# Run container detached
  - docker swarm init
  - docker stack deploy -c stackfile.yml bitroid

  - docker service ls
  - echo "Listing files"
  - ls -la
  - wget -O- localhost:8080
  
notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
