version: "3.7"

services:
    app:
        image: bitroid/bitroiddocker:latest
        ports:
            - "8181:80"
        stop_grace_period: 1m0s
        networks:
          - fronter
        deploy:
          replicas: 4
          update_config:
            parallelism: 2
            delay: 40s
          restart_policy:
            condition: on-failure
            max_attempts: 3
          placement:
            constraints: [node.role == worker]

networks:
  fronter:
