version: 2.1
orbs:
  slack: circleci/slack@1.0.0
  
jobs:
  test:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            apk --no-cache add curl
            pip install wget
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Docker build.
          command: 'docker-compose build'
      - run:
          name: Display docker images.
          command: 'docker images'
      - run:
          name: Testing the docker images.
          command: 'docker run -d --privileged -p 8080:8080 centosjenkins_jenkins'
      - run:
          name: Sleep untill docker service is up and running.
          command: 'sleep 90'
      - run:
          name: Get the container status.
          command: 'docker ps -a -s'
      - run:
          name: Get the container application status.
          command: 'wget -O- localhost:8080'
      - slack/approval-notification:
          message: Pending approval
          webhook: $NOIFY
  
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Trigger build in docker hub.
          command: $HUB_DOCKER_TRIGGER

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
