version: 2
jobs:
  test:
    docker:
      - image: ubuntu:14.04
    steps:
      - checkout
      - run: echo "Initializing build with docker stack
      - run: docker stack deploy -c stack.yml bitroid
      - run:
          name: Testing build
          command: curl localhost
  
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            - $HUB_DOCKER_TRIGGER
      
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
